name: Outline Benchmarks

on:
  workflow_dispatch:
    # Allow manual triggering only

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --all-extras

    - name: Configure Git
      run: |
        git config --global user.name "Benchmark Bot"
        git config --global user.email "benchmark@grainchain.dev"

    - name: Run benchmarks
      run: |
        uv run python benchmarks/scripts/grainchain_benchmark.py --providers local --iterations 3
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: Commit and push results
      run: |
        git add benchmarks/results/
        if ! git diff --cached --quiet; then
          git commit -m "📊 Automated benchmark results - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "No new benchmark results to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload benchmark artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: benchmark-results
        path: benchmarks/results/
        retention-days: 30
